version: '3'
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md

services:
  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    networks:
        vpn-net:
          ipv4_address: 172.110.1.2
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always     
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  openvpn:
    cap_add:
      - NET_ADMIN
    container_name: openvpn
    image: openvpn
    ports:
      - "1194:1194/udp"
      - "1194:1194/tcp"
    environment:
      - LOCAL_NETWORK=192.168.11.0/24
      - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60 -–log-driver json-file --log-opt max-size=10m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openvpn_data:/etc/openvpn
    restart: always
    networks:
      vpn-net:
        ipv4_address: 172.110.1.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pihole:
    image: pihole/pihole
    container_name: pihole
    cap_add:
      - NET_ADMIN     
    dns:
      - 127.0.0.1
      - 1.1.1.1
    depends_on:
      - openvpn
      - cloudflared
    ports:
      - "53:53"
      - "80:80"
      - "63:63/udp"
      - "443:443"
    environment:
      - "PROXY_LOCATION=pihole"
      - "VIRTUAL_PORT=80"
      - "DNS1:172.110.1.2#5053"
      - "DNS2:1.1.1.1"
      - WEBPASSWORD:1mvhMmZn
    volumes:
      - ./pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      vpn-net:
        ipv4_address: 172.110.1.4     
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

# docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
networks:
  vpn-net:
    external: true
